### ISSUE TITLE
Question: Webpack setup

### ISSUE THREAD

**Issue by mhartington** [mgechev/angular2-hot-loader#15]
Seems only system.js is shown in example snippet as well as the angular2-seed app. Would this work for something like webpack or any other bundler?

**Comment by mgechev** [comment]
Yes, it will work. At this point the main focusis to preserve as much state as possible.

Right after that I integrate webpack support.

**Comment by born2net** [comment]
sorry but not sure of the answer? "Yes, it will work" and " after that I integrate webpack support."

regards

Sean

**Comment by mgechev** [comment]
I will implement webpack support but there are tasks with higher priority at this point.

**Comment by born2net** [comment]
tx!!!!!!!!
so for now will not try Webpack and will wait for a re-post
regards
