### ISSUE TITLE
Any examples with Webpack? Compatible with Webpack?

### ISSUE THREAD

**Issue by born2net** [mgechev/angular2-hot-loader#16]
Any examples with Webpack? Is it even compatible with Webpack?

regards

Sean

**Comment by frederikschubert** [comment]
[Duplicate](https://github.com/mgechev/angular2-hot-loader/issues/15)

**Comment by born2net** [comment]
sorry but not sure of the answer? "Yes, it will work" and " after that I integrate webpack support."

regards

Sean
