### ISSUE TITLE
Compatible with webpack and browserify hmr

### ISSUE THREAD

**Issue by tamascsaba** [mgechev/angular2-hot-loader#18]
angular2-hot-loader only compatible with systemjs, but most developer use browserify or webpack.

Like: https://github.com/gaearon/react-transform-hmr which a React Transform that enables hot reloading React classes using Hot Module Replacement API. Hot module replacement is supported natively by Webpack and available in Browserify with browserify-hmr.

Webpack [API](http://webpack.github.io/docs/hot-module-replacement.html)

**Comment by mgechev** [comment]
@tamascsaba at first I'll create a component proxy which will be reusable across module loaders.

My main goals are to preserve instantiated dependencies as well as component's state. Initially the reloader will support only SystemJS, later I will add support for webpack through a configuration option.

**Comment by tamascsaba** [comment]
@mgechev it sounds good, :+1: thx
