### ISSUE TITLE
Still being worked on?

### ISSUE THREAD

**Issue by MarkPieszak** [mgechev/angular2-hot-loader#20]
@mgechev Was there any big outstanding issues, or is everything working as intended these days?

Just trying to find a HMR for Angular2, surprised there isn't an official one yet! 
Works with webpack, or only SystemJS?

**Comment by mgechev** [comment]
Hey @MarkPieszak. The project is in development but at the moment is a bit on hold.

It supports SystemJS.

**Comment by mgechev** [comment]
@MarkPieszak actually I have some progress in preserving the instantiated dependencies. 

May be by a week or two, the hot reloader will allow preservation between all bindings (including dynamic and static injectors).

**Comment by MarkPieszak** [comment]
Glad to hear it @mgechev ! 
@gdi2290 I wonder if this project is something you'd be interested in as well.

**Comment by mgechev** [comment]
@MarkPieszak @gdi2290 I'll build a component proxy which will be module system agnostic, i.e. it will be easy to reuse for webpack support.

**Comment by PatrickJS** [comment]
we can combine forces

**Comment by PatrickJS** [comment]
`react-hot-loader` was named after the webpack convention for loaders so the real name is `react-hot` and `hot` was used as it's a term in webpack for Hot Module Replacement. Dan also started a new project called `react-transform` to make the name more generic. There also needs to be a browserify version

**Comment by MarkPieszak** [comment]
I'd love to help as well :) :+1:
