### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by ambition-consulting** [mgechev/angular2-hot-loader#3]
A simple example would help using your work - which it's not meant to be, but might already be helpful to me. Also, a quick clarification in how it's different to live-reload would help in the readme.

Thanks - great work!

**Comment by mgechev** [comment]
You can find an example [here](https://github.com/mgechev/angular2-seed/tree/hot-loader). The project is still under active development (it is in an experimental branch of the angular2-seed project repository) so feedback is greatly appreciated! :-)
