### ISSUE TITLE
Feature: Allow loading of components that have been created after the page was loaded

### ISSUE THREAD

**Issue by frederikschubert** [mgechev/angular2-hot-loader#6]
Currently a page reload is needed when a new import is added to a component in the hot-reloading application. The following error is thrown when trying to add an import to an existing component:

```
Error: Failed to construct 'URL': Invalid URL
    Error loading /src/app/components/home/home.ts
    at TypeError (native)
    at l.<anonymous> (http://localhost:8080/jspm_packages/system.js:4:19228)
    at l.<anonymous> (http://localhost:8080/jspm_packages/system.js:4:23045)
    at l.<anonymous> (http://localhost:8080/jspm_packages/system.js:4:25894)
    at l.<anonymous> (http://localhost:8080/jspm_packages/system.js:5:10210)
    at l.e (http://localhost:8080/jspm_packages/system.js:5:16299)
    at l.<anonymous> (http://localhost:8080/jspm_packages/system.js:5:16371)
    at http://localhost:8080/jspm_packages/system.js:5:18303
    at promiseReactionJob (http://localhost:8080/jspm_packages/github/es-shims/es6-shim@0.34.0/es6-shim.js:2104:27)
    at http://localhost:8080/jspm_packages/github/es-shims/es6-shim@0.34.0/es6-shim.js:2396:13(anonymous function) 
 @ ng2-hot-loader.js:217promiseReactionJob 
 @ es6-shim.js:2104(anonymous function) 
 @ es6-shim.js:2117r.run 
 @ zone.min.js:3(anonymous function) 
 @ zone.min.js:3
```

The existing component with the added import (`import {Home} from "../home/home";`) looks like this:

``` typescript
import {Component} from "angular2/core";
import {Home} from "../home/home";

@Component({
    selector: "showcase",
    directives: [Home],
    templateUrl: "app/components/showCase/showCase.html"
})
export class ShowCase {

}
```

and the new component:

``` typescript
import {Component} from "angular2/core";

@Component({
    selector: "home",
    template: `
        <h3>Home</h3>
    `
})
export class Home {

}
```

**Comment by frederikschubert** [comment]
I now think that this is rather a bug with files that have relative imports. I always get the exception above when trying to reload components, that import other components.

**Comment by mgechev** [comment]
The feature is also not yet implemented.

**Comment by frederikschubert** [comment]
Ok. I had a look at the code and I now get most of how it works. The only thing I did not fully understand was the `processMessage` function. ~~Could you explain to me what `System.load` exactly does? I only knew `System.import` in that context. And also why it is necessary to call `eval` on the file's content?~~
Reading from this [entry](http://www.2ality.com/2014/09/es6-modules-final.html) it seems that `System.load` and the following `eval` are equal to `System.import`.

> Also, System.load does not load scripts, but instead will load a module and its dependencies without executing it when loading ES6 modules.

I thought that `System.import` would be sufficient to load a module and its dependencies, but I will investigate further.

**Comment by frederikschubert** [comment]
I think this issue can be closed for now. If there are any problems with the way this feature is implemented, the issue should be reopened.
